const cargoHold =['oxygen tanks', 'space suits', 'parrot', 'instruction manual', 'meal packs', 'slinky', 'security blanket'];
console.log(cargoHold);
cargoHold[5]='space tether';
console.log(cargoHold);
console.log(cargoHold.pop());
console.log(cargoHold);
console.log(cargoHold.shift());
console.log(cargoHold);
cargoHold.unshift(1138);
cargoHold.push('20 meter');
console.log(cargoHold.splice(3,0,'key'));
console.log(cargoHold);
cargoHold.splice(cargoHold.indexOf('instuction manual'),1);
console.log(cargoHold);
cargoHold.splice(2,3,'cat','fob','String cheese');
console.log(cargoHold);
