const holdCabinet1=['duct tape', 'gum', 3.14, false, 6.02223] ;
const holdCabinet2=['orange drink', 'nerf toys', 'camera', 42, 'parsnip' ];
console.log(holdCabinet1.concat(holdCabinet2));
console.log(holdCabinet1);
console.log(holdCabinet1.slice(2));
 holdCabinet2.slice (2);
holdCabinet1.reverse();
holdCabinet2.sort();
console.log(holdCabinet1);
console.log(holdCabinet2);